### ISSUE TITLE
Monterey 

### ISSUE THREAD

**Issue by mishailovic** [seathasky/Dell-Inspiron-7567-OC#1]
Have you tried to boot Monterey? If yes, can you provide the latest EFI please

**Comment by seathasky** [comment]
Yes I have and unfortunately, wifi did not work, usb mapping was somewhat screwy and trackpad failed to work as well. Those things may be possible to fix but I honestly did not bother as I just wanted something stable.

**Comment by mishailovic** [comment]
> Yes I have and unfortunately, wifi did not work, usb mapping was somewhat screwy and trackpad failed to work as well. Those things may be possible to fix but I honestly did not bother as I just wanted something stable.

Thanks anyway! I do not plan to install Monterey yet, but it would be great if there was a person who will update the EFI for Dell 7567 once in a while. Keep up your work!

**Comment by mishailovic** [comment]
Btw: did you use this version in your Monterey build? - https://github.com/OpenIntelWireless/itlwm/releases/download/v2.0.0/AirportItlwm_v2.0.0_stable_Monterey.kext.zip

**Comment by seathasky** [comment]
I havent tried it yet, but I may when holidays are done. Thanks for the link!

**Comment by mishailovic** [comment]
@seathasky Hi! Finally got it working!
![image](https://user-images.githubusercontent.com/41520056/145720616-63c2af2b-4aa0-4ed4-8b25-5bcad4eb223e.png)

Few things to mention:
1) I set ```SecureBootModel``` to ```Disabled``` as it caused ```OC: grabbed zero system-id for SB, this is not allowed.``` error (credits [here](https://github.com/tylernguyen/x1c6-hackintosh/issues/153))

2) I followed [this](https://dortania.github.io/OpenCore-Install-Guide/extras/monterey.html#bluetooth) steps to make my Bluetooth and Wi-Fi working.
